# syntax=docker/dockerfile:1.4

# ARG BASE_IMAGE_TAG="ubuntu-24.04-v4"
ARG BASE_IMAGE_TAG="ubuntu-22.04-v4"
FROM jlesage/baseimage-gui:$BASE_IMAGE_TAG

LABEL maintainer="stainless403"
LABEL description="base on jlesage/baseimage-gui:$BASE_IMAGE_TAG"

# 平台相关参数
ARG TARGETPLATFORM
ARG TARGETOS
ARG TARGETARCH
ARG TARGETVARIANT
ARG BUILDPLATFORM
ARG BUILDOS
ARG BUILDARCH
ARG BUILDVARIANT

# 配置参数
ARG APT_SOURCE_HOST="mirrors.ustc.edu.cn"
ARG PYPI_MIRROR
ARG DEFAULT_MIRROR="https://pypi.doubanio.com/simple"
ENV PYPI_MIRROR=${PYPI_MIRROR:-${DEFAULT_MIRROR}}

# 显示平台信息
RUN echo "-----Platform Information-----" && \
  echo "Target Platform: $TARGETPLATFORM ($TARGETOS/$TARGETARCH/$TARGETVARIANT)" && \
  echo "Build Platform: $BUILDPLATFORM ($BUILDOS/$BUILDARCH/$BUILDVARIANT)" && \
  echo "PYPI Mirror: $PYPI_MIRROR"

# TODO 配置apt源

# 安装基础软件包和添加PPA源
# gpg-agent:
# https://github.com/nnstreamer/nnstreamer/issues/4432
# https://github.com/nnstreamer/nnstreamer/pull/4443/files
RUN apt update -y && \
  apt install -y --no-install-recommends \
  gpg-agent \
  software-properties-common && \
  add-apt-repository ppa:deadsnakes/ppa -y && \
  apt update -y

# 安装Python 3.13和相关依赖
RUN apt install -y --no-install-recommends \
  python3.13 \
  python3.13-dev \
  python3.13-venv \
  python3-pyqt5 \
  git \
  unrar \
  wget \
  curl \
  upx-ucl \
  binutils

# 安装pip并设置Python默认版本
RUN curl -sS https://bootstrap.pypa.io/get-pip.py | python3.13 && \
  update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.13 1

# 安装工具
RUN python3.13 -m pip install pyinstaller poetry uv --verbose -i $PYPI_MIRROR

# 配置工具软链接
RUN if ! which pyinstaller > /dev/null 2>&1; then \
  ln -sf /root/.local/bin/pyinstaller /usr/local/sbin/pyinstaller; \
  fi

# 清理缓存和临时文件
RUN apt clean && \
  rm -rf /var/lib/apt/lists/* && \
  rm -rf /root/.cache/pip
