# syntax=docker/dockerfile:1.4

ARG BASE_IMAGE_TAG="ubuntu-kde-22.04"
FROM stainless403/webtop-base:$BASE_IMAGE_TAG

LABEL maintainer="stainless403"
LABEL description="base on stainless403/webtop-base:$BASE_IMAGE_TAG"

ARG TARGETPLATFORM
ARG TARGETOS
ARG TARGETARCH
ARG TARGETVARIANT

ARG BUILDPLATFORM
ARG BUILDOS
ARG BUILDARCH
ARG BUILDVARIANT

# 输出构建信息
RUN echo "-----Image platform details:" && \
  echo "Target: $TARGETPLATFORM ($TARGETOS/$TARGETARCH/$TARGETVARIANT)" && \
  echo "Build: $BUILDPLATFORM ($BUILDOS/$BUILDARCH/$BUILDVARIANT)"

RUN apt-get update -y && \
  apt-get install python3 python3-pip python3-pyqt5 \
  fonts-wqy-zenhei fonts-noto-color-emoji -y

WORKDIR /app

ENV MDCX_APP_TYPE =         "src"
ENV MDCX_CONFIG_PATH        "/mdcx-config"

RUN mkdir -p "$MDCX_CONFIG_PATH" && \
  chmod -R 777 /app && \
  chmod -R 777 "$MDCX_CONFIG_PATH"

# 写入默认的`配置文件目录`标记文件
RUN echo "$MDCX_CONFIG_PATH/config.ini" > /app/MDCx.config


COPY webtop-base/rootfs /
COPY webtop-base/rootfs-src /

RUN ln -fs /usr/share/zoneinfo/Asia/Shanghai /etc/localtime